---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE)
```

Unfortunately I'm not good enough at web dev to have properly embedded the RSVP page, so you'll have to go to a separate page :( please follow the link below.

When you get to the site, enter the password found on your RSVP to respond for all members of your household. **Please note that the passwords are case-sensitive!**

As a final request, due to issues with the web host, **we ask that you close the RSVP page as soon as your response is confirmed as submitted.** This will help us keep the site active for everyone else! Thank you!

Please submit your RSVP by **July 31, 2024**. We have to provide final numbers to our caterers by August 1, so any missing RSVPs after July 31 will be considered "No's". If you've already submitted but need to change your response, you can just resubmit the form.

RSVP here: [https://aaron-weinstock.shinyapps.io/rsvp/]( https://aaron-weinstock.shinyapps.io/rsvp/)



